# Generated by Django 5.2.6 on 2025-09-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['state', 'city'],
            },
        ),
    ]
