# Generated by Django 5.0.7 on 2024-07-26 15:10

from django.db import migrations

# A list of all the syndication data to be inserted into the database.
SYNDICATION_DATA = [
    # Alabama
    {"state": "Alabama", "city": "BIRMINGHAM", "station": "WIAT", "time": "9:00AM, 9:30AM"},
    {"state": "Alabama", "city": "HUNTSVILLE/DECATUR", "station": "WHDF", "time": "1:30AM"},
    {"state": "Alabama", "city": "MOBILE", "station": "WFGX", "time": "4:30PM"},
    # Alaska
    {"state": "Alaska", "city": "ANCHORAGE", "station": "KYUR", "time": "11:00 AM, 11:30AM"},
    {"state": "Alaska", "city": "FAIRBANKS", "station": "KATN", "time": "11:00 AM, 11:30AM"},
    # Arizona
    {"state": "Arizona", "city": "PHOENIX", "station": "KAZT", "time": "3:00PM"},
    {"state": "Arizona", "city": "TUCSON", "station": "KMSB, KTTU", "time": "10:00PM, 10:30PM"},
    {"state": "Arizona", "city": "YUMA", "station": "KECY", "time": "5:00PM, 5:30PM"},
    # Arkansas
    {"state": "Arkansas", "city": "FT. SMITH", "station": "KNXW", "time": "4:00PM, 4:30PM"},
    {"state": "Arkansas", "city": "LITTLE ROCK", "station": "KLRT", "time": "9:00AM, 9:30AM"},
    {"state": "Arkansas", "city": "JONESBORO", "station": "KJNB", "time": "3:00PM"},
    # California
    {"state": "California", "city": "BAKERSFIELD", "station": "KGET", "time": "3:00PM, 3:30PM"},
    {"state": "California", "city": "CHICO-REDDING", "station": "KCVU-DT", "time": "4:00PM, 4:30PM"},
    {"state": "California", "city": "EUREKA", "station": "KBVU", "time": "4:00PM, 4:30PM"},
    {"state": "California", "city": "FRESNO", "station": "KGPE", "time": "9:00AM, 9:30AM"},
    {"state": "California", "city": "LOS ANGELES", "station": "KCAL", "time": "12:00AM, 12:30AM"},
    {"state": "California", "city": "MONTEREY-SALINAS", "station": "KSBW", "time": "11:00AM"},
    {"state": "California", "city": "PALM SPRINGS", "station": "KPSP", "time": "9:00AM"},
    {"state": "California", "city": "SACRAMENTO", "station": "KMAX-DT", "time": "9:00PM, 9:30PM"},
    {"state": "California", "city": "SAN FRANCISCO", "station": "KPYX", "time": "10:00PM, 10:30PM"},
    {"state": "California", "city": "SAN DIEGO", "station": "KGTV", "time": "1:30AM, 2:00AM"},
    {"state": "California", "city": "SANTA BARBARA", "station": "KEYE-D3", "time": "9:00AM, 9:30AM"},
    # Colorado
    {"state": "Colorado", "city": "COLORADO SPRINGS", "station": "KOAA", "time": "11:00AM, 11:30AM"},
    {"state": "Colorado", "city": "DENVER", "station": "KWGN", "time": "1:00PM, 1:30PM"},
    {"state": "Colorado", "city": "GRAND JUNCTION", "station": "KFQX", "time": "1:00PM, 1:30PM"},
    # Connecticut
    {"state": "Connecticut", "city": "HARTFORD", "station": "WCTX", "time": "4:30PM, 3:00AM"},
    # District of Columbia
    {"state": "District of Columbia", "city": "WASHINGTON DC", "station": "WDVM", "time": "2:00PM, 2:30PM"},
    # Florida
    {"state": "Florida", "city": "FT. MYERS", "station": "WFTX", "time": "12:00PM, 12:30PM"},
    {"state": "Florida", "city": "JACKSONVILLE", "station": "WFOX", "time": "2:00PM, 2:30PM"},
    {"state": "Florida", "city": "GAINESVILLE", "station": "WCJB", "time": "3:00PM"},
    {"state": "Florida", "city": "MIAMI-FT. LAUDERDALE", "station": "WSVN-2", "time": "7:30PM, 1:06AM"},
    {"state": "Florida", "city": "TAMPA", "station": "WTOG", "time": "7:00PM, 7:30PM"},
    {"state": "Florida", "city": "TALLAHASSEE", "station": "WTXL", "time": "11:30AM, 12:00PM"},
    {"state": "Florida", "city": "PANAMA CITY", "station": "WECP", "time": "12:30PM, 2:00PM"},
    {"state": "Florida", "city": "PENSACOLA", "station": "WFGX", "time": "4:30PM"},
    {"state": "Florida", "city": "ORLANDO", "station": "WRDQ", "time": "5:00PM, 5:30PM"},
    {"state": "Florida", "city": "WEST PALM BEACH", "station": "WTCN-CA", "time": "4:00PM, 5:30AM"},
    # Georgia
    {"state": "Georgia", "city": "ATLANTA", "station": "WPCH", "time": "4:00PM"},
    {"state": "Georgia", "city": "AUGUSTA", "station": "WRDW", "time": "12:00PM"},
    {"state": "Georgia", "city": "MACON", "station": "WGXA-DT", "time": "12:00PM"},
    {"state": "Georgia", "city": "SAVANNAH", "station": "WTGS", "time": "5:00PM, 5:30PM"},
    # Hawaii
    {"state": "Hawaii", "city": "HONOLULU", "station": "KOHN-D2", "time": "10:00AM, 10:30AM, 12:00PM"},
    # Idaho
    {"state": "Idaho", "city": "BOISE", "station": "KIVI", "time": "2:00PM, 2:30PM"},
    {"state": "Idaho", "city": "IDAHO FALLS/POCATELLO", "station": "KIFI-D3", "time": "1:00PM, 1:30PM"},
    {"state": "Idaho", "city": "TWIN FALLS", "station": "KSAW", "time": "2:00PM, 2:30PM"},
    # Illinois
    {"state": "Illinois", "city": "CHAMPAIGN/SPRINGFIELD", "station": "WAND", "time": "11:00AM, 11:30AM"},
    {"state": "Illinois", "city": "ROCKFORD", "station": "WSLN", "time": "11:00AM"},
    {"state": "Illinois", "city": "PEORIA", "station": "WEEK-D3", "time": "10:00AM, 10:30AM"},
    {"state": "Illinois", "city": "CHICAGO", "station": "WCIU", "time": "7:30PM, 12:00-1:30AM"},
    # Indiana
    {"state": "Indiana", "city": "FT. WAYNE", "station": "WANE", "time": "9:30AM, 10:00AM"},
    {"state": "Indiana", "city": "EVANSVILLE", "station": "WEVV", "time": "9:00AM, 9:30AM"},
    {"state": "Indiana", "city": "INDIANAPOLIS", "station": "WISH", "time": "2:00PM, 2:30PM"},
    {"state": "Indiana", "city": "LAFAYETTE", "station": "WPBI", "time": "3:30PM, 4:00PM"},
    {"state": "Indiana", "city": "SOUTH BEND", "station": "WCWW", "time": "4:30PM, 1:30AM"},
    {"state": "Indiana", "city": "TERRE HAUTE", "station": "WTWO", "time": "12:30PM"},
    # Iowa
    {"state": "Iowa", "city": "CEDAR RAPIDS", "station": "KCRG", "time": "12:30PM"},
    {"state": "Iowa", "city": "DAVENPORT", "station": "KLJB", "time": "3:30PM"},
    {"state": "Iowa", "city": "DES MOINES", "station": "KDSM", "time": "10:00AM, 10:30AM"},
    {"state": "Iowa", "city": "OTTUMWA", "station": "KTVO", "time": "3:00PM, 3:30PM"},
    {"state": "Iowa", "city": "SIOUX CITY", "station": "KCAU", "time": "2:00PM, 2:30PM"},
    # Kansas
    {"state": "Kansas", "city": "KANSAS CITY", "station": "KSHB", "time": "3:00PM, 2:30AM"},
    {"state": "Kansas", "city": "TOPEKA", "station": "KTKA-TV", "time": "9:00AM, 9:30AM"},
    {"state": "Kansas", "city": "WICHITA", "station": "KSAS-DT", "time": "4:30PM"},
    # Kentucky
    {"state": "Kentucky", "city": "LEXINGTON", "station": "WDKY", "time": "1:00PM, 1:30PM"},
    {"state": "Kentucky", "city": "LOUISVILLE", "station": "WBKI", "time": "3:00PM, 3:30PM"},
    {"state": "Kentucky", "city": "PADUCAH", "station": "WPSD", "time": "2:00PM"},
    # Louisiana
    {"state": "Louisiana", "city": "ALEXANDRIA", "station": "WALB", "time": "12:00PM, 2:00AM"},
    {"state": "Louisiana", "city": "BATON ROUGE", "station": "WBXH", "time": "3:00PM, 3:30PM"},
    {"state": "Louisiana", "city": "LAFAYETTE", "station": "KATC", "time": "3:30PM, 1:00AM"},
    {"state": "Louisiana", "city": "MONROE", "station": "KNOE", "time": "3:30PM, 1:30AM"},
    {"state": "Louisiana", "city": "NEW ORLEANS", "station": "WVUE", "time": "12:30PM"},
    {"state": "Louisiana", "city": "SHREVEPORT", "station": "KTBS, KPHJ", "time": "2:00PM, 2:30PM"},
    # Maine
    {"state": "Maine", "city": "PORTLAND", "station": "WGNE", "time": "9:00AM"},
    # Maryland
    {"state": "Maryland", "city": "BALTIMORE", "station": "WJZ", "time": "3:00PM, 3:30PM"},
    {"state": "Maryland", "city": "SALISBURY", "station": "WRDE", "time": "3:00PM, 3:30PM"},
    # Massachusetts
    {"state": "Massachusetts", "city": "BOSTON", "station": "WSBK", "time": "10:00PM, 10:30PM"},
    {"state": "Massachusetts", "city": "SPRINGFIELD", "station": "WSHM", "time": "4:00PM, 4:30PM"},
    # Michigan
    {"state": "Michigan", "city": "DETROIT", "station": "WKBD", "time": "11:00PM, 11:30PM"},
    {"state": "Michigan", "city": "FLINT-SAGINAW", "station": "WEYI", "time": "12:00PM, 12:30PM"},
    {"state": "Michigan", "city": "GRAND RAPIDS", "station": "WWMT", "time": "3:30PM"},
    {"state": "Michigan", "city": "LANSING", "station": "WLNS", "time": "4:00PM, 4:30PM"},
    {"state": "Michigan", "city": "ALPENA", "station": "WBKB", "time": "5:00PM, 5:30PM"},
    {"state": "Michigan", "city": "TRAVERSE CITY", "station": "WGTU", "time": "10:30AM"},
    # Minnesota
    {"state": "Minnesota", "city": "DULUTH", "station": "KQDS", "time": "11:00AM, 11:30AM"},
    {"state": "Minnesota", "city": "MINNEAPOLIS-ST. PAUL", "station": "WCCO", "time": "3:00PM, 3:30PM"},
    # Mississippi
    {"state": "Mississippi", "city": "COLUMBUS-TUPELO", "station": "WCBI-D2", "time": "4:00PM, 4:30PM"},
    {"state": "Mississippi", "city": "GREENWOOD-GREENVILLE", "station": "WXVT-LD", "time": "12:00PM"},
    {"state": "Mississippi", "city": "HATTIESBURG", "station": "WHPM", "time": "4:00PM"},
    {"state": "Mississippi", "city": "JACKSON", "station": "WJTV-D2", "time": "10:00AM, 10:30AM"},
    {"state": "Mississippi", "city": "MERIDIAN", "station": "WMDN", "time": "4:00PM, 4:30PM"},
    # Missouri
    {"state": "Missouri", "city": "COLUMBIA", "station": "WOMU", "time": "3:00PM, 3:30PM"},
    {"state": "Missouri", "city": "JOPLIN", "station": "KFJX", "time": "2:30PM, 4:30PM"},
    {"state": "Missouri", "city": "SPRINGFIELD", "station": "KRBK", "time": "1:00PM, 1:30PM"},
    {"state": "Missouri", "city": "ST. JOSEPH", "station": "KQTV", "time": "3:00PM, 3:30PM, 11:00AM"},
    {"state": "Missouri", "city": "ST. LOUIS", "station": "KDNL", "time": "2:30PM, 12:00AM"},
    # Montana
    {"state": "Montana", "city": "BILLINGS", "station": "KSVI", "time": "5:00PM, 5:30PM"},
    {"state": "Montana", "city": "BUTTE", "station": "KWYB", "time": "3:00PM, 3:30PM"},
    {"state": "Montana", "city": "GREAT FALLS", "station": "KFBB", "time": "3:00PM, 3:30PM"},
    {"state": "Montana", "city": "HELENA", "station": "KHBB", "time": "3:00PM, 3:30PM"},
    {"state": "Montana", "city": "MISSOULA", "station": "KTMF", "time": "3:00PM, 3:30PM"},
    # Nebraska
    {"state": "Nebraska", "city": "LINCOLN", "station": "KLKN", "time": "2:00PM, 2:30PM"},
    {"state": "Nebraska", "city": "OMAHA", "station": "KETV", "time": "3:00PM"},
    # Nevada
    {"state": "Nevada", "city": "LAS VEGAS", "station": "KVCW-D2", "time": "8:00AM, 5:00AM"},
    {"state": "Nevada", "city": "RENO", "station": "KRVN", "time": "2:00PM, 2:30PM"},
    # New Mexico
    {"state": "New Mexico", "city": "ALBUQUERQUE-SANTA FE", "station": "KQRE-D2", "time": "4:00PM, 4:30PM"},
    # New York
    {"state": "New York", "city": "ALBANY", "station": "WXXA", "time": "3:00PM, 3:30PM"},
    {"state": "New York", "city": "BINGHAMTON", "station": "WBNG", "time": "9:00AM"},
    {"state": "New York", "city": "BUFFALO", "station": "WNYO-DT", "time": "10:00AM, 10:30AM"},
    {"state": "New York", "city": "ELMIRA", "station": "WETM", "time": "2:00PM, 2:30PM"},
    {"state": "New York", "city": "NEW YORK CITY", "station": "WLNY", "time": "6:00PM, 6:30PM"},
    {"state": "New York", "city": "ROCHESTER", "station": "WROC", "time": "9:00AM, 9:30AM"},
    {"state": "New York", "city": "SYRACUSE", "station": "WSYR", "time": "3:00PM, 3:30PM"},
    {"state": "New York", "city": "UTICA", "station": "WKTV-D2", "time": "5:00PM, 5:30PM"},
    {"state": "New York", "city": "WATERTOWN", "station": "WWTI", "time": "3:00PM, 3:30PM"},
    # North Carolina
    {"state": "North Carolina", "city": "CHARLOTTE", "station": "WXAN", "time": "6:00PM, 6:30PM"},
    {"state": "North Carolina", "city": "GREENVILLE-SPARTANBURG", "station": "WLOS-D2", "time": "10:30AM, 2:30AM"},
    {"state": "North Carolina", "city": "GREENVILLE-NEW BERN", "station": "WYDO", "time": "5:00PM, 5:30PM"},
    {"state": "North Carolina", "city": "GREENSBORO-HIGH POINT", "station": "WCWG", "time": "4:00PM, 4:30PM"},
    {"state": "North Carolina", "city": "RALEIGH-DURHAM", "station": "WRAZ-DT", "time": "11:00AM, 2:30AM"},
    # North Dakota
    {"state": "North Dakota", "city": "FARGO", "station": "KVRR", "time": "11:00AM, 11:30AM"},
    # Ohio
    {"state": "Ohio", "city": "CINCINNATI", "station": "WCPO", "time": "7:30PM"},
    {"state": "Ohio", "city": "CLEVELAND", "station": "WUAB", "time": "5:00PM, 5:30PM"},
    {"state": "Ohio", "city": "COLUMBUS", "station": "WSYX", "time": "10:00AM, 10:30AM"},
    {"state": "Ohio", "city": "DAYTON", "station": "WHIO", "time": "10:30AM"},
    {"state": "Ohio", "city": "TOLEDO", "station": "WTVG", "time": "9:00AM, 9:30AM"},
    {"state": "Ohio", "city": "YOUNGSTOWN", "station": "WKBN", "time": "9:00AM, 9:30AM"},
    # Oklahoma
    {"state": "Oklahoma", "city": "OKLAHOMA CITY", "station": "KOCB", "time": "5:00PM"},
    {"state": "Oklahoma", "city": "TULSA", "station": "KJRH", "time": "2:30PM"},
    # Oregon
    {"state": "Oregon", "city": "BEND", "station": "KOHD", "time": "11:00AM, 11:30AM"},
    {"state": "Oregon", "city": "EUGENE", "station": "KEVU", "time": "1:00PM, 1:30PM"},
    {"state": "Oregon", "city": "MEDFORD", "station": "KNOE", "time": "11:00AM, 11:30AM"},
    {"state": "Oregon", "city": "PORTLAND", "station": "KPDX", "time": "6:00PM, 6:30PM"},
    # Pennsylvania
    {"state": "Pennsylvania", "city": "ERIE", "station": "WFXP", "time": "1:00AM"},
    {"state": "Pennsylvania", "city": "HARRISBURG", "station": "WHP-D3", "time": "6:00PM, 6:30PM"},
    {"state": "Pennsylvania", "city": "PHILADELPHIA", "station": "WPSG", "time": "9:00PM, 9:30PM"},
    {"state": "Pennsylvania", "city": "PITTSBURGH", "station": "WPXI", "time": "11:00AM"},
    {"state": "Pennsylvania", "city": "WILKES-BARRE", "station": "WOLF", "time": "9:30AM, 10:00AM"},
    # Rhode Island
    {"state": "Rhode Island", "city": "PROVIDENCE", "station": "WLNE", "time": "12:30PM, 4:30PM"},
    # South Carolina
    {"state": "South Carolina", "city": "AIKEN", "station": "WRDW", "time": "12:00PM, 12:30PM"},
    {"state": "South Carolina", "city": "CHARLESTON", "station": "SCIV-DT", "time": "11:00AM, 11:30AM"},
    {"state": "South Carolina", "city": "COLUMBIA", "station": "WIS-D2", "time": "9:00AM"},
    {"state": "South Carolina", "city": "MYRTLE BEACH", "station": "WBTW", "time": "3:00PM"},
    # South Dakota
    {"state": "South Dakota", "city": "FARGO", "station": "KVRR", "time": "11:00AM, 11:30AM"},
    # Tennessee
    {"state": "Tennessee", "city": "CHATTANOOGA", "station": "WRCB", "time": "2:00PM, 2:30PM"},
    {"state": "Tennessee", "city": "JACKSON", "station": "WJKT", "time": "8:00AM, 8:30AM"},
    {"state": "Tennessee", "city": "KNOXVILLE", "station": "WBXX", "time": "1:00PM, 1:30PM"},
    {"state": "Tennessee", "city": "MEMPHIS", "station": "WATN", "time": "2:30PM"},
    {"state": "Tennessee", "city": "NASHVILLE", "station": "WZTV-D2", "time": "9:30AM, 6:00AM"},
    {"state": "Tennessee", "city": "TRI-CITIES", "station": "WJHL-D2", "time": "5:00PM, 5:30PM"},
    # Texas
    {"state": "Texas", "city": "ABILENE", "station": "KXVA", "time": "7:00AM, 8:30AM"},
    {"state": "Texas", "city": "AMARILLO", "station": "KCPN-DT", "time": "4:00PM, 4:30PM"},
    {"state": "Texas", "city": "AUSTIN", "station": "KNVA-DT", "time": "3:30AM"},
    {"state": "Texas", "city": "BEAUMONT", "station": "KFDM-D3", "time": "4:00PM, 12:30AM"},
    {"state": "Texas", "city": "CORPUS CHRISTI", "station": "KRIS", "time": "11:00AM, 11:30AM"},
    {"state": "Texas", "city": "DALLAS", "station": "KTXA", "time": "8:30PM, 4:00PM"},
    {"state": "Texas", "city": "EL PASO", "station": "KVIA", "time": "2:00PM, 2:30PM"},
    {"state": "Texas", "city": "HARLINGEN", "station": "KVEO-D2", "time": "9:00AM, 9:30AM"},
    {"state": "Texas", "city": "HOUSTON", "station": "KPRC", "time": "3:00AM"},
    {"state": "Texas", "city": "SAN ANGELO", "station": "KIDY", "time": "7:00AM, 8:30AM"},
    {"state": "Texas", "city": "SAN ANTONIO", "station": "KCWX", "time": "6:00PM, 6:30PM"},
    {"state": "Texas", "city": "TYLER", "station": "KTPN-LD", "time": "2:00PM"},
    {"state": "Texas", "city": "VICTORIA", "station": "KVCT", "time": "2:30PM"},
    {"state": "Texas", "city": "WACO", "station": "KEKT-DT", "time": "11:00AM, 11:30AM"},
    # Utah
    {"state": "Utah", "city": "SALT LAKE CITY", "station": "KJZZ", "time": "4:00PM, 2:30AM"},
    # Vermont
    {"state": "Vermont", "city": "BURLINGTON", "station": "WCAX", "time": "TBD"},
    # Virginia
    {"state": "Virginia", "city": "NORFOLK", "station": "WTKR, WGNT", "time": "7:30PM, TBD"},
    {"state": "Virginia", "city": "RICHMOND", "station": "WWBT, WUPV", "time": "TBD"},
    {"state": "Virginia", "city": "ROANOKE", "station": "WSLS", "time": "3:00PM, 3:30PM"},
    # Washington
    {"state": "Washington", "city": "SEATTLE-TACOMA", "station": "KSTW", "time": "10:00PM, 10:30PM"},
    {"state": "Washington", "city": "SPOKANE", "station": "KREM, KSKN", "time": "11:00AM, 11:30AM"},
    # West Virginia
    {"state": "West Virginia", "city": "CHARLESTON", "station": "WOWK", "time": "9:00AM, 9:30AM"},
    {"state": "West Virginia", "city": "WHEELING", "station": "WTOV-D2", "time": "7:00PM, 7:30PM"},
    {"state": "West Virginia", "city": "BLUEFIELD", "station": "WVVA", "time": "12:00PM, 3:00AM"},
    # Wisconsin
    {"state": "Wisconsin", "city": "GREEN BAY", "station": "WCWF", "time": "4:30PM"},
    {"state": "Wisconsin", "city": "LA CROSSE-EAU CLAIRE", "station": "WLAX", "time": "11:00AM, 11:30AM"},
    {"state": "Wisconsin", "city": "MADISON", "station": "WMSN", "time": "1:00PM, 1:30PM"},
    {"state": "Wisconsin", "city": "MILWAUKEE", "station": "WMLW", "time": "7:00PM, 7:30PM"},
    {"state": "Wisconsin", "city": "WAUSAU", "station": "WSAW", "time": "TBD"},
    # Wyoming
    {"state": "Wyoming", "city": "CASPER", "station": "KFNB", "time": "3:00PM, 3:30PM"},
    {"state": "Wyoming", "city": "CHEYENNE", "station": "KLWY", "time": "3:00PM, 3:30PM"},
]

def populate_syndication_data(apps, schema_editor):
    """
    Populates the Syndication model with the initial data set.
    """
    Syndication = apps.get_model('archives', 'Syndication')
    # Use bulk_create for efficiency
    syndication_entries = [
        Syndication(
            state=entry['state'],
            city=entry['city'],
            station=entry['station'],
            time=entry['time']
        ) for entry in SYNDICATION_DATA
    ]
    Syndication.objects.bulk_create(syndication_entries)

def unpopulate_syndication_data(apps, schema_editor):
    """
    Deletes all data from the Syndication model.
    """
    Syndication = apps.get_model('archives', 'Syndication')
    Syndication.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_syndication'), # Assumes the previous migration was named this
    ]

    operations = [
        migrations.RunPython(populate_syndication_data, unpopulate_syndication_data),
    ]
