# Generated by Django 5.2.6 on 2025-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_populate_syndication_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fast_line_tiebreaker_winner_podium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fast_line_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
