# Generated by Django 5.2.6 on 2025-09-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_game_fast_line_tiebreaker_winner_podium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fast_line_score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='StatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('through_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.game')),
            ],
        ),
    ]
