# Generated by Django 5.2.6 on 2025-09-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_alter_player_fast_line_score_statisticscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('order_description', models.CharField(help_text="e.g., 'Lowest to Highest' or 'West to East'", max_length=255)),
                ('seed_name', models.CharField(max_length=255)),
                ('seed_value', models.CharField(blank=True, max_length=100, null=True)),
                ('seed_order', models.IntegerField()),
                ('item1_name', models.CharField(max_length=255)),
                ('item1_value', models.CharField(blank=True, max_length=100, null=True)),
                ('item1_order', models.IntegerField()),
                ('item2_name', models.CharField(max_length=255)),
                ('item2_value', models.CharField(blank=True, max_length=100, null=True)),
                ('item2_order', models.IntegerField()),
                ('item3_name', models.CharField(max_length=255)),
                ('item3_value', models.CharField(blank=True, max_length=100, null=True)),
                ('item3_order', models.IntegerField()),
                ('item4_name', models.CharField(max_length=255)),
                ('item4_value', models.CharField(blank=True, max_length=100, null=True)),
                ('item4_order', models.IntegerField()),
                ('episode_correct_count', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_lines', to='archives.game')),
            ],
            options={
                'ordering': ['game', 'round_number'],
                'unique_together': {('game', 'round_number')},
            },
        ),
    ]
