# Generated by Django 5.2.6 on 2025-09-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_preliminaryline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('SECONDARY', 'Secondary'), ('SCOREKEEPER', 'Scorekeeper'), ('BETA_TESTER', 'Beta Tester'), ('ADMIN', 'Admin')], default='BASIC', max_length=50),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('prelim', 'Preliminary'), ('fast', 'Fast Line'), ('final', 'Final Line')], max_length=10)),
                ('play_type', models.CharField(choices=[('solo', 'Solo'), ('ai', 'vs. AI'), ('multi', 'Multiplayer')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game_played', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.game')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
